#!/bin/bash

set -e

. `dirname $0`/../global_config.py





kinit -kt $KERBEROS_KEYTAB $KERBEROS_PRINCIPAL

mkdir -p $LOCAL_PATH_PREFIX/$3
# cd $LOCAL_PATH_PREFIX/caddr
# mis_date=$(date -d "$1 +1 day" +%Y-%m-%d)
# dt_id_simple=$(date -d "$1" +%Y-%m-%d)
csv_file=$LOCAL_PATH_PREFIX/$3/$3_$2.csv

mode=${2:-auto}

if [ "$mode" == copy ];
then
    exit 0
fi

query="$1"
echo Executing "$query"
`dirname $0`/mysql "$1" > $csv_file

if [ `cat $csv_file | wc -l` -eq 1 ];
then
    if [ "$mode" == ingest ];
    then
        exit 1
    else
        exit 0
    fi
fi

hadoop fs -mkdir -p $HDFS_PATH_PREFIX/source/$3
hadoop fs -put -f $csv_file $HDFS_PATH_PREFIX/source/$3/
