#create a dictionary
target_names = [-1, 1]

value = {'transaction_amount': 0,
         'amtratio30d': 30, 
         'amtratio60d': 60, 
         'amtratio90d': 90, 
         'trx30s': 30,
         'trx1m': 1, 
         'trx30m': 30, 
         'trx1h': 1, 
         'dest1m': 1, 
         'dest30m': 30, 
         'dest_acc': 0, 
         'acc': 0,
         'inout5m': 5, 
         'inout30m': 30, 
         'inout1h': 1, 
         'ibft_in': 1,
         'ibft_out': 1,
         'trx_dec': 1, 
         'trx_5k': 1, 
         'trx_10k': 1,
         'time_0_5': 0, 
         'time_0_3': 0, 
         'time_21_0': 0,
         'velocity': 0}

print(value)

unit = {'transaction_amount': "seconds",
        'amtratio30d': "days", 
         'amtratio60d': "days", 
         'amtratio90d': "days", 
         'trx30s': "seconds",
         'trx1m': "minutes", 
         'trx30m': "minutes", 
         'trx1h': "hours", 
         'dest1m': "minutes", 
         'dest30m': "minutes", 
         'dest_acc': "seconds", 
         'acc': "seconds",
         'inout5m': "minutes", 
         'inout30m': "minutes", 
         'inout1h': "hours",
         'ibft_in': "days",
         'ibft_out': "days", 
         'trx_dec': "months", 
         'trx_5k': "days", 
         'trx_10k': "days",
         'time_0_5': "seconds", 
         'time_0_3': "seconds", 
         'time_21_0': "seconds",
         'velocity': "seconds"}

print(unit)

type = {'transaction_amount': "basic",
        'amtratio30d': "ratio_avg_trx_amt", 
         'amtratio60d': "ratio_avg_trx_amt", 
         'amtratio90d': "ratio_avg_trx_amt", 
         'trx30s': "timeseries_trx_cnt",
         'trx1m': "timeseries_trx_cnt", 
         'trx30m': "timeseries_trx_cnt", 
         'trx1h': "timeseries_trx_cnt", 
         'dest1m': "timeseries_trx_dest_cnt", 
         'dest30m': "timeseries_trx_dest_cnt", 
         'dest_acc': "dest_acc_cnt", 
         'acc': "acc_cnt",
         'inout5m': "ratio_in_out", 
         'inout30m': "ratio_in_out", 
         'inout1h': "ratio_in_out",
         'ibft_in': "ibft",
         'ibft_out': "ibft", 
         'trx_dec': "seasonal_trx", 
         'trx_5k': "smallamt_trx_cnt", 
         'trx_10k': "smallamt_trx_cnt",
         'time_0_5': "timerange_trx_cnt", 
         'time_0_3': "timerange_trx_cnt", 
         'time_21_0': "timerange_trx_cnt",
         'velocity': "velocity"
       }

print(type)

source = {'transaction_amount': "transfer",
         'amtratio30d': "transfer", 
         'amtratio60d': "transfer", 
         'amtratio90d': "transfer", 
         'trx30s': "transfer:sender",
         'trx1m': "transfer:sender", 
         'trx30m': "transfer:sender", 
         'trx1h': "transfer:sender", 
         'dest1m': "transfer:receiver", 
         'dest30m': "transfer:receiver", 
         'dest_acc': "transfer:receiver", 
         'acc': "transfer:sender",
         'inout5m': "transfer", 
         'inout30m': "transfer", 
         'inout1h': "transfer",
         'ibft_in': "transfer:receiver",
         'ibft_out': "transfer:sender", 
         'trx_dec': "transfer:sender", 
         'trx_5k': "transfer:sender", 
         'trx_10k': "transfer:sender",
         'time_0_5': "transfer:sender", 
         'time_0_3': "transfer:sender", 
         'time_21_0': "transfer:sender",
         'velocity': "transfer:sender"}

print(source)

filters = {'transaction_amount': "",
         'amtratio30d': '{"value": {"transaction_id": ["$transaction_id", "!="]}}', 
         'amtratio60d': '{"value": {"transaction_id": ["$transaction_id", "!="]}}', 
         'amtratio90d': '{"value": {"transaction_id": ["$transaction_id", "!="]}}', 
         'trx30s': '{"value": {"transaction_id": ["$transaction_id", "!="]}}',
         'trx1m': '{"value": {"transaction_id": ["$transaction_id", "!="]}}', 
         'trx30m': '{"value": {"transaction_id": ["$transaction_id", "!="]}}', 
         'trx1h': '{"value": {"transaction_id": ["$transaction_id", "!="]}}', 
         'dest1m': '{"value": {"transaction_id": ["$transaction_id", "!="]}}', 
         'dest30m': '{"value": {"transaction_id": ["$transaction_id", "!="]}}', 
         'dest_acc': '{"value": {"transaction_id": ["$transaction_id", "!="]}}', 
         'acc': '{"value": {"transaction_id": ["$transaction_id", "!="]}}',
         'inout5m': '{"value": {"transaction_id": ["$transaction_id", "!="]}}', 
         'inout30m': '{"value": {"transaction_id": ["$transaction_id", "!="]}}', 
         'inout1h': '{"value": {"transaction_id": ["$transaction_id", "!="]}}',
         'ibft_in': '{"value": {"transaction_id": ["$transaction_id", "!="]}}',
         'ibft_out': '{"value": {"transaction_id": ["$transaction_id", "!="]}}', 
         'trx_dec': '{"value": {"transaction_id": ["$transaction_id", "!="]}}', 
         'trx_5k': '{"value": {"transaction_id": ["$transaction_id", "!="], "transaction_amount":[5000,"<="]}}', 
         'trx_10k': '{"value": {"transaction_id": ["$transaction_id", "!="], "transaction_amount":[10000,"<="]}}',
         'time_0_5': '{"value": {"transaction_id": ["$transaction_id","!="], "transaction_time": [["00:00","05:00"],"between"]}}', 
         'time_0_3': '{"value": {"transaction_id": ["$transaction_id","!="], "transaction_time": [["00:00","03:00"],"between"]}}', 
         'time_21_0': '{"value": {"transaction_id": ["$transaction_id","!="], "transaction_time": [["21:00","23:59"],"between"]}}',
         'velocity': '{"value": {"transaction_id": ["$transaction_id","!="]}}'}

print(filters)